# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/pydev-handbook',
                'doc_host': 'https://ankur-aiwg.github.io',
                'git_url': 'https://github.com/ankur-aiwg/pydev-handbook',
                'lib_path': 'pydev_handbook'},
  'syms': {'pydev_handbook.core': {'pydev_handbook.core.foo': ('core.html#foo', 'pydev_handbook/core.py')}}}
