# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/pydev-handbook',
                'doc_host': 'https://ankur-aiwg.github.io',
                'git_url': 'https://github.com/ankur-aiwg/pydev-handbook',
                'lib_path': 'pydev_handbook'},
  'syms': { 'pydev_handbook.aitoolssetup': {'pydev_handbook.aitoolssetup.foo': ('aitoolssetup.html#foo', 'pydev_handbook/aitoolssetup.py')},
            'pydev_handbook.devenvsetup': {'pydev_handbook.devenvsetup.foo': ('devenvsetup.html#foo', 'pydev_handbook/devenvsetup.py')},
            'pydev_handbook.introduction': { 'pydev_handbook.introduction.foo': ( 'introduction.html#foo',
                                                                                  'pydev_handbook/introduction.py')}}}
