"""An overview of the Python Developer's Handbook"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_introduction.ipynb.

# %% auto 0
__all__ = ['foo']

# %% ../nbs/00_introduction.ipynb 6
def foo(): pass
